// <auto-generated />
using Autospace2.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Autospace2.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210317111037_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Autospace2.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Description1",
                            Name = "Product1"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Description2",
                            Name = "Product2"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Description3",
                            Name = "Product3"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Description4",
                            Name = "Product4"
                        });
                });

            modelBuilder.Entity("Autospace2.Models.ProductShop", b =>
                {
                    b.Property<int>("ShopId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("ShopId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductShop");

                    b.HasData(
                        new
                        {
                            ShopId = 1,
                            ProductId = 1
                        },
                        new
                        {
                            ShopId = 1,
                            ProductId = 2
                        },
                        new
                        {
                            ShopId = 1,
                            ProductId = 4
                        },
                        new
                        {
                            ShopId = 2,
                            ProductId = 1
                        },
                        new
                        {
                            ShopId = 2,
                            ProductId = 3
                        },
                        new
                        {
                            ShopId = 3,
                            ProductId = 2
                        },
                        new
                        {
                            ShopId = 3,
                            ProductId = 4
                        });
                });

            modelBuilder.Entity("Autospace2.Models.Shop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Schedule")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Shops");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Address1",
                            Name = "Shop1",
                            Schedule = "11-19"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Address2",
                            Name = "Shop2",
                            Schedule = "10-18"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Address3",
                            Name = "Shop3",
                            Schedule = "12-20"
                        });
                });

            modelBuilder.Entity("Autospace2.Models.ProductShop", b =>
                {
                    b.HasOne("Autospace2.Models.Product", "Product")
                        .WithMany("ProductShops")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Autospace2.Models.Shop", "Shop")
                        .WithMany("ProductShops")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("Autospace2.Models.Product", b =>
                {
                    b.Navigation("ProductShops");
                });

            modelBuilder.Entity("Autospace2.Models.Shop", b =>
                {
                    b.Navigation("ProductShops");
                });
#pragma warning restore 612, 618
        }
    }
}
